config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.save
    redirect_to @message
  end

  private
    def message_params
      params.require(:message).permit(:name, :org, :contract, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<table>
  <tr>
    <th>姓名</th> 
    <th>单位</th>
    <th>联系方式</th>
    <th>问题描述</th>
  </tr>
  <% @messages.each do |message| %>
    <tr>
      <td><%= message.name %></td>
      <td><%= message.org %></td>
      <td><%= message.contract %></td>
      <td><%= message.text %></td>
      <td><%= link_to 'Show', message_path(message) %></td>
    </tr>
  <% end %>
</table>

app/views/messages/new.html.erb
<%= form_with scope: :message, url: messages_path,  local: true do |form| %>

<div class="form"> 
  <p>
    <%= form.label :姓名 %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :单位 %><br>
    <%= form.text_field :org %>
  </p>

  <p>
    <%= form.label :联系方式 %><br>
    <%= form.text_field :contract %>
  </p>

  <p>
    <%= form.label :问题描述 %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

</div>

<% end %>

app/views/messages/show.html.erb
<p>
  <strong>姓名</strong>
  <%= @message.name %>
</p>

<p>
  <strong>单位</strong>
  <%= @message.org %>
</p>

<p>
  <strong>联系方式</strong>
  <%= @message.contract %>
</p>

<p>
  <strong>问题描述</strong>
  <%= @message.text %>
</p>

<p>
  <h1>提交成功，请保持电话畅通。</h1>
</p>